# This file is a template, and might need editing to fit your project.
#
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic CI/CD pipeline for building a Docker image.
#
# You'll need to activate shared runners on your project to run this pipeline.
#
# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - build

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main

build-tags:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags